#!/usr/bin/env bash
#    vvvv vvvv-- the code from above
GREEN='\033[0;32m'
NC='\033[0m'

test_sources_dir="./test-sources"
compiler="./xpp.out"

if [ ! -f "$compiler" ]; then
    echo "Binário do analisador não foi encontrado. Você compilou o projeto?"
    exit 1;
fi

for test_file in "$test_sources_dir"/*.lsi; 
do
  printf "\n\n=========================================\n\n${GREEN}Executando arquivo de teste '$test_file'${NC}:\n"
  grep '^\s*/\?\*' $test_file | tr -d '*/'  
  $compiler < $test_file
done
